version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./worker-management-server
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${API_PORT}
    ports:
      - "8080:5000"
  postgres:
    image: postgres:14.4
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # react-app:
  #   build:
  #     dockerfile: Dockerfile
  #     context: /worker-management-frontend
  #   environment:
  #     NODE_ENV: development
  #     PORT: 3000
  #   ports:
  #     - "3000:3000"
