version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:1234@postgres:5432/wms_db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "8080:3000"
  postgres:
    image: postgres:14.4
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: wms_db
      